service: campaign-management

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    DB_HOST: 'campaign-markdb01.cr2ceugwq8m6.us-east-2.rds.amazonaws.com'
    DB_USER: 'admin017'
    DB_PASSWORD: 'adp4$worDrd5'
    DB_NAME: 'campaignDB'
  layers:
    - arn:aws:lambda:us-east-1:047719647865:layer:mysql-layer:1

functions:
  createCampaign:
    handler: handler.createCampaign
    events:
      - http:
          path: campaigns
          method: post
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  listCampaigns:
    handler: handler.listCampaigns
    events:
      - http:
          path: campaigns
          method: get
  getMessages:
    handler: handler.getMessages
    events:
      - http:
          path: campaigns/{id}/messages
          method: get
  sendCampaign:
    handler: handler.sendCampaign
    events:
      - http:
          path: campaigns/{id}/send
          method: post

package:
  exclude:
    - node_modules/**
    - test/**
    - .git/**
    - layer/**
  

  
  # getCampaign:
  #   handler: handler.getCampaign
  #   events:
  #     - http:
  #         path: campaigns/{id}
  #         method: get

  
